# Desativar o banner do Spring Boot
spring.main.banner-mode=off
logging.pattern.console=

# Configurações do servidor MCP
spring.ai.mcp.server.name=CodeReview MCP Server
spring.ai.mcp.server.version=0.1.0

spring.ai.mcp.server.stdio=true

# Configurações de logging
logging.level.root=INFO
logging.level.com.codereview.mcp=DEBUG
logging.level.org.springframework.ai.mcp=DEBUG
logging.file.name=./model-context-protocol/codereview/codereview.log
# logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n

server.port=8081